GET localhost:9000/api/tasks

###

POST localhost:9000/api/tasks
Content-Type: application/json

{
  "id": 1,
  "title": "Dokończyć zadanie",
  "author": "Luk",
  "deadline": [2019,12,3]
}

###

DELETE localhost:9000/api/tasks/1

###
PUT localhost:9000/api/tasks

###
