GET localhost:9000/api/tasks

###

POST localhost:9000/api/tasks
Content-Type: application/json

{
  "title": "Dokończyć zadanie",
  "description": "AAAAAA"
}

###

DELETE localhost:9000/api/tasks/1

###
PUT localhost:9000/api/tasks/10
Content-Type: application/json

{
  "title": "Dokończyć zadanie z modulu 1",
  "description": "Zarejestrować się na Facebooko"
}
###
